### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by kutyel** [Tecnativa/docker-ocb#3]
I think we should add to the _README_ something like this:
# Useful commands

``` sh
docker-compose -f development.yml up -d     # starts all the containers
docker-compose -f development.yml logs -f   # outputs containers log to the console
docker-compose -f development.yml stop      # stops all the containers
```

Any other idea or improvement that the team (@Tecnativa) thinks is worth adding?

**Comment by pedrobaeza** [comment]
Good idea. @Yajo, what do you think? Is it too obvious for any non-newbie?

**Comment by yajo** [comment]
A good candidate for [this section](https://github.com/Tecnativa/docker-ocb#using-this-for-development).
